version: "3.9"

services:
  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=samples
    volumes:
      - .:/var/www/samples
      - ~/.composer/auth.json:/root/.composer/auth.json
      - ~/.aws:/root/.aws
    networks:
      - samples-php

networks:
  samples-php: